// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WksJobsMvc.Data;

#nullable disable

namespace WksJobsMvc.Migrations
{
    [DbContext(typeof(WksDbContext))]
    [Migration("20231005064626_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WksJobsMvc.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("JobItemDetailId")
                        .HasColumnType("int");

                    b.Property<string>("MaterialDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PerUnitCost")
                        .HasColumnType("float");

                    b.Property<string>("UnitOfMeasurement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.HasIndex("JobItemDetailId");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("WksJobsMvc.Models.Job", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HoursWorked")
                        .HasColumnType("int");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("JobCode");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobItemDetailId")
                        .HasColumnType("int");

                    b.Property<string>("JobStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JobType");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfDays")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPersons")
                        .HasColumnType("int");

                    b.Property<int>("ThirdPartyServiceCost")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("JobCode")
                        .IsUnique();

                    b.HasIndex("JobItemDetailId");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("WksJobsMvc.Models.JobItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<float>("ItemNetTotal")
                        .HasColumnType("real");

                    b.Property<float>("ItemQty")
                        .HasColumnType("real");

                    b.Property<float>("ItemRate")
                        .HasColumnType("real");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobItemDetail", (string)null);
                });

            modelBuilder.Entity("WksJobsMvc.Models.JobType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JobTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobType", (string)null);
                });

            modelBuilder.Entity("WksJobsMvc.Models.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VesselCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VesselType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VesselCode")
                        .IsUnique();

                    b.ToTable("Vessel", (string)null);
                });

            modelBuilder.Entity("WksJobsMvc.Models.Item", b =>
                {
                    b.HasOne("WksJobsMvc.Models.JobItemDetail", null)
                        .WithMany("Items")
                        .HasForeignKey("JobItemDetailId");
                });

            modelBuilder.Entity("WksJobsMvc.Models.Job", b =>
                {
                    b.HasOne("WksJobsMvc.Models.JobItemDetail", null)
                        .WithMany("Jobs")
                        .HasForeignKey("JobItemDetailId");
                });

            modelBuilder.Entity("WksJobsMvc.Models.JobItemDetail", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
